version: '3.2'
services:

 zookeeper:
  image: confluentinc/cp-zookeeper:${CP_KAFKA_VERSION}
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
   KAFKA_OPTS: |-
    -Djava.security.auth.login.config=/etc/zookeeper/jaas.conf
    -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    -Dzookeeper.requireClientAuthScheme=sasl
  volumes:
   - ./conf/zookeeper/jaas.conf:/etc/zookeeper/jaas.conf
  healthcheck:
   test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
   start_period: 30s

  kafka:
   image: confluentinc/cp-kafka:5.4.1
   ports:
    - "9092:9092"
   depends_on:
    - zookeeper
   volumes:
    - type: bind
      source: ./secrets
      target: /etc/kafka/secrets
   environment:
    KAFKA_BROKER_ID: 1
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_ADVERTISED_LISTENERS: SSL://localhost:9092
    KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    KAFKA_SSL_KEYSTORE_FILENAME: kafka.broker1.keystore.jks
    KAFKA_SSL_KEYSTORE_CREDENTIALS: broker1_keystore_creds
    KAFKA_SSL_KEY_CREDENTIALS: broker1_sslkey_creds
    KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.broker1.truststore.jks
    KAFKA_SSL_TRUSTSTORE_CREDENTIALS: broker1_truststore_creds
    KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
    KAFKA_SSL_CLIENT_AUTH: required
    KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
    KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
