version: '2'
services:
  
  zookeeper:
    image: confluentinc/cp-zookeeper:${CP_KAFKA_VERSION}
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:${CP_KAFKA_VERSION}
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN 
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
  telegraf:
    image: telegraf:1.15
    depends_on:
     - kafka
    volumes:
     - ./telegraf-plain.conf:/etc/telegraf/telegraf.conf

  kafkacat:
    image: confluentinc/cp-kafkacat:${CP_KAFKA_VERSION}
    depends_on:
     - kafka
    command: "kafkacat -b kafka:9092 -C -K: -f '\nKey (%K bytes): %k\t\nValue (%S bytes): %s\n\Partition: %p\tOffset: %o\n--\n' -t telegraf"
