 zookeeper:
  image: confluentinc/cp-zookeeper:${CP_KAFKA_VERSION}
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
   KAFKA_OPTS: |-
    -Djava.security.auth.login.config=/etc/zookeeper/jaas.conf
    -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
    -Dzookeeper.requireClientAuthScheme=sasl
  volumes:
   - ./conf/zookeeper/jaas.conf:/etc/zookeeper/jaas.conf
  healthcheck:
   test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
   start_period: 30s
