version: '3.4'
services:

 zookeeper:
  image: confluentinc/cp-zookeeper:${CP_KAFKA_VERSION}
  environment:
   ZOOKEEPER_CLIENT_PORT: 2181
   ZOOKEEPER_TICK_TIME: 2000
   KAFKA_OPTS: |-
    -Djava.security.auth.login.config=/etc/zookeeper/jaas.conf 
    -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider 
    -Dzookeeper.requireClientAuthScheme=sasl
  volumes:
   - ./conf/zookeeper/jaas.conf:/etc/zookeeper/jaas.conf
  healthcheck:
   test: ["CMD", "bash", "-c", "echo ruok | nc localhost 2181 | grep imok"]
   start_period: 30s

 kafka:
  image: confluentinc/cp-server:${CP_KAFKA_VERSION}
  depends_on:
   - zookeeper
  environment:
   KAFKA_OPTS: -Djdk.tls.rejectClientInitiatedRenegotiation=true -Djava.security.auth.login.config=/etc/kafka/jaas.conf
   KAFKA_BROKER_ID: 1
   KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   KAFKA_ADVERTISED_LISTENERS: SSL://kafka:9092
   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_SSL_KEYSTORE_FILENAME: kafka.jks
   KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.creds
   KAFKA_SSL_KEY_CREDENTIALS: kafka.creds
   KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.jks
   KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.creds
   KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
   KAFKA_SSL_CLIENT_AUTH: required
   KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
   KAFKA_LISTENER_NAME_INTERNAL_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
   KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
   KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer

   KAFKA_LOG4J_ROOT_LOGLEVEL: WARN 
   KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR 
   KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
   CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
   KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
#  KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
   CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: SSL://kafka:9092
   CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
   CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
   CONFLUENT_METRICS_ENABLE: 'false'
  volumes:
   - ./conf/kafka/jaas.conf:/etc/kafka/jaas.conf
   - ./conf/kafka/keys/kafka.key:/etc/kafka/kafka.key
   - ./conf/kafka/keys/kafka.crt:/etc/kafka/kafka.crt
   - ./conf/kafka/keys/kafka.pem:/etc/kafka/kafka.pem
   - ./conf/kafka/keys/kafka.jks:/etc/kafka/secrets/kafka.jks
   - ./conf/kafka/keys/kafka_keystore_creds:/etc/kafka/secrets/kafka.creds
  healthcheck:
   test: ["CMD", "nc", "127.0.0.1", "9093"]
   start_period: 30s

 telegraf-to-kafka:
# image: telegraf:1.15
  image: telegraf:sasl-test
  depends_on:
   - kafka
  volumes:
   - ./conf/telegraf/telegraf-out.conf:/etc/telegraf/telegraf.conf
   

 telegraf:
# image: telegraf:1.15
  image: telegraf:sasl-test
  depends_on:
   - kafka
   - telegraf-to-kafka
  volumes:
   - ./conf/telegraf/telegraf-in.conf:/etc/telegraf/telegraf.conf
